FROM postgres:13

# Configurar variables de entorno predeterminadas
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=mydb

# Exponer el puerto
EXPOSE 5432

# Comando por defecto
CMD ["postgres"]