FROM redis:6

# Configuración adicional (opcional)
# Por ejemplo, puedes copiar un archivo de configuración personalizado
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Comando por defecto
CMD ["redis-server"]