apiVersion: kuma.io/v1alpha1
kind: TrafficLog
mesh: default
metadata:
  name: log-all-traffic
  namespace: poc-kuma
spec:
  sources:
    - match:
        kuma.io/service: "*"
  destinations:
    - match:
        kuma.io/service: "*"
  conf:
    backend: default